### PR TITLE
Enable cross-building for Scala 2.11 and 2.12

### PR DESCRIPTION
**Pull request by RomanIakovlev**
Update dependencies versions to ones supporting Scala 2.12, modify the
code to accomodate for Rediscala API changes.

### CODE REVIEW

**Comment by everpeace** [comment]
@RomanIakovlev Thanks for your contribution!!  I will review this in this few days because my job is in peak. sorry for your inconvenience.

**Comment by everpeace** [comment]
@RomanIakovlev  Thank you very much again for supporting cross build!!  Looks Good To Me!

**Comment by everpeace** [comment]
After merging this, I will
- set up cross build for travis ci
- release 0.0.3 for `2.11.8`, `2.12.1`

**Comment by RomanIakovlev** [comment]
@everpeace thank you very much for merging this! Looking forward for a release.

**Comment by everpeace** [comment]
@RomanIakovlev I just released [`0.0.4`](https://bintray.com/everpeace/maven/constructr-redis/0.0.4).  Please enjoy :-) !

Note: Because I missed releasing 0.0.3 in cross build, I released cross built 0.0.4 just after that.

**Pull request merged**
