### PR TITLE
Update dependencies versions

### LINKED ISSUE #4: Update for version 0.14.0
With version 0.14.0 this extension is not able to be instantiated anymore. 
My guess is that the constructor should be adjusted so that the prefix is not needed anymore.

```code
[ERROR] [11/04/2016 12:30:56.936] [my-app-akka.actor.default-dispatcher-18] [akka://my-app-akka/user/$a] A Coordination implementation must provide a constructor with the following signature:
(clusterName: String, system: ActorSystem)
akka.actor.ActorInitializationException: akka://my-app/user/$a: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Exception: A Coordination implementation must provide a constructor with the following signature:
(clusterName: String, system: ActorSystem)
	at de.heikoseeberger.constructr.coordination.Coordination$.apply(Coordination.scala:37)
	at de.heikoseeberger.constructr.Constructr.createConstructrMachine(Constructr.scala:91)
	at de.heikoseeberger.constructr.Constructr.<init>(Constructr.scala:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at akka.util.Reflect$.instantiate(Reflect.scala:44)
	at akka.actor.NoArgsReflectConstructor.produce(IndirectActorProducer.scala:105)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 more
```

### PR DESCRIPTION
**Pull request by RomanIakovlev**
Update to actual versions of ConstuctR and Akka. Modify code to
accomodate for ConstructR changes, remove deprecated ActorDSL
references. Also fixes #4.

### CODE REVIEW

**Comment by everpeace** [comment]
@RomanIakovlev Thanks for your PR!! Looks Great 👍

**Comment by RomanIakovlev** [comment]
@everpeace thanks for merging this. Could I please ask you to make a release with these changes?

**Comment by everpeace** [comment]
@RomanIakovlev Sure, I'm working on it. Could you please wait for a while?

**Comment by everpeace** [comment]
@RomanIakovlev `0.0.2` was released! Thanks for your contribution!!

**Comment by RomanIakovlev** [comment]
Thanks a lot! Sorry, I didn't mean to put any pressure in terms of urgency.

**Comment by everpeace** [comment]
@RomanIakovlev Please don't mind :-)  I would like to release new version too because `0.0.1` depended on obsolete akka and constructr versions.

**Pull request merged**
